-- Generated by node scripts/build-sql.cjs. Run in Supabase SQL Editor as postgres.
-- Existing projects with the September 14 upgrade applied. No inventory data changes.
begin;
create schema if not exists iae_internal;
revoke all on schema iae_internal from public;
create table if not exists iae_internal.migrations(version text primary key,applied_at timestamptz not null default now());
do $iae_apply$ begin
if not exists(select 1 from iae_internal.migrations where version='202609150002_function_security.sql') then
execute $iae_ddl$-- Both bodies use schema-qualified relations; pg_catalog built-ins remain available.
alter function public.set_updated_at() set search_path = '';
alter function public.protect_field_key() set search_path = '';

-- Supabase may grant EXECUTE to anon/authenticated directly through default ACLs.
-- Revoking only from PUBLIC does not remove those independent grants.
do $permissions$
declare signature text; target regprocedure;
begin
  foreach signature in array array[
    'public.set_updated_at()',
    'public.protect_field_key()',
    'public.handle_new_user()',
    'public.guard_inventory_integrity()',
    'public.protect_last_admin()',
    'public.protect_occupied_container()',
    'public.sync_template_category()',
    'public.validate_inventory_fields()',
    'public.guard_logistics_request_status()',
    'public.record_logistics_request_history()',
    'public.guard_logistics_request_article()'
  ] loop
    target := to_regprocedure(signature);
    -- The article-reference migration may not yet exist when applying this patch alone.
    if target is null and signature = 'public.guard_logistics_request_article()' then continue; end if;
    if target is null then raise exception 'Falta la funcion %. Aplica primero la actualizacion de logistica.', signature; end if;
    execute format('revoke execute on function %s from public, anon, authenticated', target);
  end loop;

  -- Required RPCs and RLS helpers. Their bodies enforce active profiles, roles and sites.
  foreach signature in array array[
    'public.user_role()',
    'public.user_headquarters_id()',
    'public.can_manage_logistics_requests(uuid)',
    'public.create_inventory_record(jsonb,uuid,numeric,text)',
    'public.place_inventory_item(uuid,text,uuid,uuid,numeric,text)',
    'public.record_inventory_movement(uuid,text,numeric,text,uuid)',
    'public.update_inventory_item(uuid,text,text,text,date,date,numeric,text)',
    'public.update_catalog_field(uuid,text,text,text,jsonb)'
  ] loop
    target := to_regprocedure(signature);
    if target is null then raise exception 'Falta la funcion %. Aplica primero la actualizacion de logistica.', signature; end if;
    execute format('revoke execute on function %s from public, anon, authenticated', target);
    execute format('grant execute on function %s to authenticated', target);
  end loop;
end $permissions$;

notify pgrst, 'reload schema';
$iae_ddl$;
insert into iae_internal.migrations(version) values('202609150002_function_security.sql');
end if;
end $iae_apply$;
commit;
