-- Generated by node scripts/build-sql.cjs. Run in Supabase SQL Editor as postgres.
begin;
create schema if not exists iae_internal;
revoke all on schema iae_internal from public;
create table if not exists iae_internal.migrations(version text primary key,applied_at timestamptz not null default now());
do $iae_apply$ begin
if not exists(select 1 from iae_internal.migrations where version='202609140001_security_and_operations.sql') then
execute $iae_ddl$create or replace function public.user_role() returns text
language sql stable security definer set search_path = public
as $$ select r.code from public.profiles p join public.app_roles r on r.id = p.role_id
where p.id = auth.uid() and p.is_active $$;

create or replace function public.user_headquarters_id() returns uuid
language sql stable security definer set search_path = public
as $$ select p.headquarters_id from public.profiles p where p.id = auth.uid() and p.is_active $$;

revoke all on function public.user_role() from public;
revoke all on function public.user_headquarters_id() from public;
grant execute on function public.user_role(), public.user_headquarters_id() to authenticated;

alter table public.profiles add column if not exists is_logistics_contact boolean not null default false;
alter table public.inventory_items add column if not exists operational_status text not null default 'available'
  check (operational_status in ('available', 'in_use', 'repair', 'inspection', 'retired'));
-- Legacy maintenance records must not become available during the upgrade.
update public.inventory_items set operational_status='inspection'
where status='maintenance' and operational_status='available';
alter table public.inventory_items add column if not exists lot_code text;
alter table public.inventory_items alter column current_stock type numeric(14,3);
alter table public.inventory_items alter column minimum_stock type numeric(14,3);
alter table public.inventory_movements alter column quantity type numeric(14,3);
alter table public.inventory_container_items alter column quantity type numeric(14,3);
alter table public.inventory_movements add column if not exists balance_after numeric(14,3);
alter table public.inventory_movements add column if not exists request_id uuid;
create unique index if not exists inventory_movement_request_idx on public.inventory_movements(request_id);
alter table public.inventory_items drop constraint if exists inventory_stock_nonnegative;
alter table public.inventory_items add constraint inventory_stock_nonnegative check (current_stock >= 0 and (minimum_stock is null or minimum_stock >= 0)) not valid;

create table if not exists public.inventory_item_history (
  id uuid primary key default gen_random_uuid(),
  item_id uuid not null references public.inventory_items(id) on delete restrict,
  actor_id uuid references public.profiles(id),
  event_type text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists item_history_item_idx on public.inventory_item_history(item_id,created_at desc);
create table if not exists public.inventory_attachments (
  id uuid primary key default gen_random_uuid(),
  item_id uuid not null references public.inventory_items(id) on delete cascade,
  title text not null,
  url text not null check (url ~ '^https://'),
  created_by uuid references public.profiles(id),
  created_at timestamptz not null default now()
);
alter table public.inventory_item_history enable row level security;
alter table public.inventory_attachments enable row level security;
drop policy if exists "Read visible history" on public.inventory_item_history;
create policy "Read visible history" on public.inventory_item_history for select to authenticated
using (exists (select 1 from public.inventory_items i where i.id=item_id));
drop policy if exists "Read visible attachments" on public.inventory_attachments;
create policy "Read visible attachments" on public.inventory_attachments for select to authenticated
using (exists (select 1 from public.inventory_items i where i.id=item_id));
drop policy if exists "Admins manage attachments" on public.inventory_attachments;
create policy "Admins manage attachments" on public.inventory_attachments for all to authenticated
using (public.user_role()='admin') with check (public.user_role()='admin');

-- Editors can create their own site's records, but cannot change existing resources.
drop policy if exists "Admins and editors manage inventory" on public.inventory_items;
drop policy if exists "Operators and admins manage inventory" on public.inventory_items;
drop policy if exists "Admins manage inventory" on public.inventory_items;
create policy "Admins manage inventory" on public.inventory_items for all to authenticated
using (public.user_role()='admin') with check (public.user_role()='admin');
drop policy if exists "Editors create inventory" on public.inventory_items;
create policy "Editors create inventory" on public.inventory_items for insert to authenticated
with check (public.user_role() in ('editor','operator') and headquarters_id=public.user_headquarters_id() and created_by=auth.uid());

drop policy if exists "Admins and editors manage movements" on public.inventory_movements;
drop policy if exists "Operators and admins manage movements" on public.inventory_movements;
drop policy if exists "Admins and editors manage relations" on public.inventory_item_relations;
drop policy if exists "Admins and operators manage relations" on public.inventory_item_relations;
drop policy if exists "Admins manage relations" on public.inventory_item_relations;
create policy "Admins manage relations" on public.inventory_item_relations for all to authenticated
using (public.user_role()='admin') with check (public.user_role()='admin');
drop policy if exists "Admins and editors manage container items" on public.inventory_container_items;
drop policy if exists "Admins manage container items" on public.inventory_container_items;
create policy "Admins manage container items" on public.inventory_container_items for all to authenticated
using (public.user_role()='admin') with check (public.user_role()='admin');
drop policy if exists "Admins and editors manage alerts" on public.alerts;
drop policy if exists "Admins and operators manage alerts" on public.alerts;
drop policy if exists "Admins manage alerts" on public.alerts;
create policy "Admins manage alerts" on public.alerts for all to authenticated
using (public.user_role()='admin') with check (public.user_role()='admin');

drop policy if exists "Headquarters readable by authenticated users" on public.headquarters;
create policy "Headquarters readable by authenticated users" on public.headquarters for select to authenticated
using (public.user_role()='admin' or id=public.user_headquarters_id());
drop policy if exists "Inventory readable by authenticated users" on public.inventory_items;
create policy "Inventory readable by authenticated users" on public.inventory_items for select to authenticated
using (public.user_role()='admin' or (public.user_role() is not null and headquarters_id=public.user_headquarters_id()));

create or replace function public.guard_inventory_integrity() returns trigger
language plpgsql security definer set search_path = public as $$
declare h uuid; other_h uuid; q numeric;
begin
  -- Serializes hierarchy/placement changes and prevents check/write races.
  perform pg_advisory_xact_lock(90714001);
  if tg_table_name='locations' then
    if new.headquarters_id is null then raise exception 'La ubicacion necesita sede'; end if;
    if new.parent_location_id is not null then
      select headquarters_id into h from public.locations where id=new.parent_location_id;
      if h is distinct from new.headquarters_id then raise exception 'La ubicacion padre debe ser de la misma sede'; end if;
      if exists (with recursive ancestors as (
        select id,parent_location_id from public.locations where id=new.parent_location_id
        union select l.id,l.parent_location_id from public.locations l join ancestors a on l.id=a.parent_location_id
      ) select 1 from ancestors where id=new.id) then raise exception 'La jerarquia de ubicaciones contiene un ciclo'; end if;
    end if;
    if tg_op='UPDATE' and old.headquarters_id is distinct from new.headquarters_id and (
      exists(select 1 from public.inventory_items where location_id=new.id) or
      exists(select 1 from public.inventory_containers where location_id=new.id) or
      exists(select 1 from public.locations where parent_location_id=new.id)
    ) then raise exception 'Mueve el contenido antes de cambiar la sede'; end if;
  elsif tg_table_name='inventory_containers' then
    if new.location_id is not null then
      select headquarters_id into h from public.locations where id=new.location_id;
      if h is distinct from new.headquarters_id then raise exception 'La caja y su ubicacion deben pertenecer a la misma sede'; end if;
    end if;
    if tg_op='UPDATE' and old.headquarters_id is distinct from new.headquarters_id and exists(
      select 1 from public.inventory_container_items where container_id=new.id
    ) then raise exception 'Vacia la caja antes de cambiar su sede'; end if;
  elsif tg_table_name='inventory_items' then
    if new.headquarters_id is null then raise exception 'El articulo necesita sede'; end if;
    if new.location_id is not null then
      select headquarters_id into h from public.locations where id=new.location_id;
      if h is distinct from new.headquarters_id then raise exception 'Articulo y ubicacion deben ser de la misma sede'; end if;
      if exists(select 1 from public.inventory_container_items where item_id=new.id) then raise exception 'El articulo ya esta en una caja'; end if;
    end if;
    if exists(select 1 from public.inventory_container_items ci join public.inventory_containers c on c.id=ci.container_id
      where ci.item_id=new.id and c.headquarters_id is distinct from new.headquarters_id) then raise exception 'La caja pertenece a otra sede'; end if;
  elsif tg_table_name='inventory_container_items' then
    select headquarters_id,current_stock into h,q from public.inventory_items where id=new.item_id for update;
    select headquarters_id into other_h from public.inventory_containers where id=new.container_id;
    if h is null or h is distinct from other_h then raise exception 'Caja y articulo deben pertenecer a la misma sede'; end if;
    if exists(select 1 from public.inventory_items where id=new.item_id and location_id is not null) then raise exception 'El articulo tiene ubicacion directa'; end if;
    if new.quantity <> q then raise exception 'La cantidad de la caja debe ser el stock completo de esta partida'; end if;
  elsif tg_table_name='inventory_item_relations' then
    select headquarters_id into h from public.inventory_items where id=new.source_item_id;
    select headquarters_id into other_h from public.inventory_items where id=new.target_item_id;
    if new.source_item_id=new.target_item_id or h is null or h is distinct from other_h then raise exception 'Relacion invalida o entre sedes diferentes'; end if;
  end if;
  return new;
end $$;

do $$ declare t text; begin
  foreach t in array array['locations','inventory_containers','inventory_items','inventory_container_items','inventory_item_relations'] loop
    execute format('drop trigger if exists guard_inventory_integrity on public.%I',t);
    execute format('create trigger guard_inventory_integrity before insert or update on public.%I for each row execute function public.guard_inventory_integrity()',t);
  end loop;
end $$;

create or replace function public.place_inventory_item(p_item_id uuid,p_type text,p_location_id uuid default null,p_container_id uuid default null,p_quantity numeric default 1,p_notes text default null)
returns void language plpgsql security definer set search_path = public as $$
declare i public.inventory_items; previous jsonb;
begin
  if public.user_role() <> 'admin' or public.user_role() is null then raise exception 'Solo administradores pueden reubicar articulos'; end if;
  perform pg_advisory_xact_lock(90714001);
  select * into i from public.inventory_items where id=p_item_id for update;
  if not found then raise exception 'Articulo no encontrado'; end if;
  if p_type not in ('none','location','container') or p_type is null then raise exception 'Destino invalido'; end if;
  if p_type='location' and not exists(select 1 from public.locations where id=p_location_id and headquarters_id=i.headquarters_id and is_active) then raise exception 'Ubicacion no valida para esta sede'; end if;
  if p_type='container' then
    if not exists(select 1 from public.inventory_containers where id=p_container_id and headquarters_id=i.headquarters_id and is_active) then raise exception 'Caja no valida para esta sede'; end if;
    if p_quantity is null or p_quantity<=0 or p_quantity<>i.current_stock then raise exception 'Mueve la partida completa; para repartirla crea partidas separadas'; end if;
  end if;
  previous=jsonb_build_object('location_id',i.location_id,'container_id',(select container_id from public.inventory_container_items where item_id=i.id));
  delete from public.inventory_container_items where item_id=i.id;
  update public.inventory_items set location_id=case when p_type='location' then p_location_id else null end where id=i.id;
  if p_type='container' then insert into public.inventory_container_items(container_id,item_id,quantity,notes) values(p_container_id,i.id,p_quantity,p_notes); end if;
  insert into public.inventory_item_history(item_id,actor_id,event_type,details) values(i.id,auth.uid(),'placement',jsonb_build_object('before',previous,'type',p_type,'location_id',p_location_id,'container_id',p_container_id,'notes',p_notes));
end $$;

create or replace function public.record_inventory_movement(p_item_id uuid,p_type text,p_quantity numeric,p_notes text,p_request_id uuid)
returns numeric language plpgsql security definer set search_path = public as $$
declare i public.inventory_items; balance numeric; previous public.inventory_movements;
begin
  if public.user_role() is distinct from 'admin' then raise exception 'Solo administradores pueden registrar movimientos'; end if;
  if p_request_id is null then raise exception 'Falta el identificador de movimiento'; end if;
  perform pg_advisory_xact_lock(90714001);
  select * into previous from public.inventory_movements where request_id=p_request_id;
  if found then
    if previous.item_id<>p_item_id or previous.movement_type<>p_type or previous.quantity<>p_quantity or previous.notes is distinct from p_notes then raise exception 'Identificador reutilizado con datos distintos'; end if;
    return previous.balance_after;
  end if;
  select * into i from public.inventory_items where id=p_item_id for update;
  if not found then raise exception 'Articulo no encontrado'; end if;
  if p_type is null or p_type not in ('in','out','adjustment') or p_quantity is null or p_quantity<0 or p_quantity<>round(p_quantity,3) or (p_type<>'adjustment' and p_quantity=0) then raise exception 'Cantidad o movimiento invalido'; end if;
  if length(trim(coalesce(p_notes,'')))<3 then raise exception 'Indica el motivo del movimiento'; end if;
  balance=case p_type when 'in' then i.current_stock+p_quantity when 'out' then i.current_stock-p_quantity else p_quantity end;
  if balance<0 then raise exception 'Stock insuficiente'; end if;
  update public.inventory_items set current_stock=balance,
    status=case when expiration_date<current_date then 'expired' when minimum_stock is not null and balance<=minimum_stock then 'low' else 'ok' end where id=i.id;
  if balance=0 then delete from public.inventory_container_items where item_id=i.id;
  else update public.inventory_container_items set quantity=balance where item_id=i.id; end if;
  insert into public.inventory_movements(item_id,movement_type,quantity,notes,created_by,balance_after,request_id)
    values(i.id,p_type,p_quantity,p_notes,auth.uid(),balance,p_request_id);
  return balance;
end $$;

create or replace function public.update_inventory_item(p_item_id uuid,p_name text,p_description text,p_status text,p_maintenance_due_at date,p_expiration_date date,p_minimum_stock numeric,p_notes text)
returns void language plpgsql security definer set search_path = public as $$
declare i public.inventory_items;
begin
  if public.user_role() is distinct from 'admin' then raise exception 'Solo administradores pueden editar articulos'; end if;
  perform pg_advisory_xact_lock(90714001);
  select * into i from public.inventory_items where id=p_item_id for update;
  if not found then raise exception 'Articulo no encontrado'; end if;
  if length(trim(coalesce(p_name,'')))<2 or p_status is null or p_status not in ('available','in_use','repair','inspection','retired') or p_minimum_stock<0 or length(trim(coalesce(p_notes,'')))<3 then raise exception 'Revisa nombre, estado, stock minimo y motivo'; end if;
  update public.inventory_items set name=trim(p_name),description=p_description,operational_status=p_status,
    maintenance_due_at=p_maintenance_due_at,expiration_date=p_expiration_date,minimum_stock=p_minimum_stock,
    status=case when p_expiration_date<current_date then 'expired' when p_minimum_stock is not null and current_stock<=p_minimum_stock then 'low' else 'ok' end where id=i.id;
  insert into public.inventory_item_history(item_id,actor_id,event_type,details) values(i.id,auth.uid(),'update',jsonb_build_object('before',to_jsonb(i),'status',p_status,'notes',p_notes));
end $$;

-- New records and initial placement are committed together, including editor creation.
create or replace function public.create_inventory_record(p_record jsonb,p_container_id uuid default null,p_quantity numeric default null,p_notes text default null)
returns uuid language plpgsql security definer set search_path = public as $$
declare new_id uuid; h uuid; r text; stock numeric;
begin
  r=public.user_role(); h=(p_record->>'headquarters_id')::uuid;
  if r is null or r not in ('admin','editor','operator') or (r<>'admin' and h is distinct from public.user_headquarters_id()) then raise exception 'No tienes permiso para crear en esta sede'; end if;
  if not exists(select 1 from public.headquarters where id=h and is_active) then raise exception 'Sede no disponible'; end if;
  perform pg_advisory_xact_lock(90714001);
  stock=coalesce((p_record->>'current_stock')::numeric,0);
  if stock<0 then raise exception 'Stock invalido'; end if;
  insert into public.inventory_items(name,slug,template_id,category,subtype,description,technical_specs,sku,serial_number,headquarters_id,location_id,is_consumable,minimum_stock,current_stock,unit,expiration_date,maintenance_due_at,status,created_by,lot_code)
  select p_record->>'name',p_record->>'slug',t.id,t.category_code,p_record->>'subtype',p_record->>'description',coalesce(p_record->'technical_specs','{}'::jsonb),p_record->>'sku',p_record->>'serial_number',h,(p_record->>'location_id')::uuid,coalesce((p_record->>'is_consumable')::boolean,false),(p_record->>'minimum_stock')::numeric,stock,p_record->>'unit',(p_record->>'expiration_date')::date,(p_record->>'maintenance_due_at')::date,
    case when (p_record->>'expiration_date')::date<current_date then 'expired' when stock<=(p_record->>'minimum_stock')::numeric then 'low' else 'ok' end,auth.uid(),p_record->>'lot_code'
  from public.inventory_templates t where t.id=(p_record->>'template_id')::uuid returning id into new_id;
  if new_id is null then raise exception 'Plantilla no encontrada'; end if;
  if p_container_id is not null then
    if not exists(select 1 from public.inventory_containers where id=p_container_id and headquarters_id=h and is_active) then raise exception 'Caja no disponible en esta sede'; end if;
    insert into public.inventory_container_items(container_id,item_id,quantity,notes) values(p_container_id,new_id,stock,p_notes);
  end if;
  insert into public.inventory_item_history(item_id,actor_id,event_type,details) values(new_id,auth.uid(),'created',jsonb_build_object('stock',stock));
  return new_id;
end $$;

create or replace function public.protect_last_admin() returns trigger language plpgsql security definer set search_path=public as $$
begin
  perform pg_advisory_xact_lock(90714002);
  if old.is_active and exists(select 1 from public.app_roles where id=old.role_id and code='admin') and
    (not new.is_active or new.role_id<>old.role_id) and not exists(
      select 1 from public.profiles p join public.app_roles r on r.id=p.role_id where p.id<>old.id and p.is_active and r.code='admin'
    ) then raise exception 'No puedes desactivar o cambiar el rol del ultimo administrador'; end if;
  return new;
end $$;
drop trigger if exists protect_last_admin on public.profiles;
create trigger protect_last_admin before update on public.profiles for each row execute function public.protect_last_admin();

-- Technical keys are stable identifiers; labels remain editable.
create or replace function public.protect_field_key() returns trigger language plpgsql as $$
begin
  if (new.field_key<>old.field_key or new.field_type<>old.field_type) and exists(select 1 from public.inventory_template_fields where field_id=old.id) then
    raise exception 'Un campo asignado no puede cambiar de clave o tipo. Crea otro campo y conserva el historial';
  end if;
  return new;
end $$;
drop trigger if exists protect_field_key on public.inventory_fields;
create trigger protect_field_key before update on public.inventory_fields for each row execute function public.protect_field_key();

revoke all on function public.place_inventory_item(uuid,text,uuid,uuid,numeric,text) from public;
revoke all on function public.record_inventory_movement(uuid,text,numeric,text,uuid) from public;
revoke all on function public.update_inventory_item(uuid,text,text,text,date,date,numeric,text) from public;
revoke all on function public.create_inventory_record(jsonb,uuid,numeric,text) from public;
grant execute on function public.place_inventory_item(uuid,text,uuid,uuid,numeric,text), public.record_inventory_movement(uuid,text,numeric,text,uuid), public.update_inventory_item(uuid,text,text,text,date,date,numeric,text), public.create_inventory_record(jsonb,uuid,numeric,text) to authenticated;
grant select on public.inventory_item_history,public.inventory_attachments to authenticated;
grant insert,update,delete on public.inventory_attachments to authenticated;

$iae_ddl$;
insert into iae_internal.migrations(version) values('202609140001_security_and_operations.sql');
end if;
end $iae_apply$;

do $iae_apply$ begin
if not exists(select 1 from iae_internal.migrations where version='202609140002_logistics_requests.sql') then
execute $iae_ddl$-- Depends on 202609140001: active-user helpers and is_logistics_contact.
create function public.can_manage_logistics_requests(p_headquarters_id uuid)
returns boolean language sql stable security definer set search_path = public
as $$
  select coalesce(public.user_role() = 'admin' or (
    public.user_role() is not null
    and p_headquarters_id = public.user_headquarters_id()
    and exists (select 1 from public.profiles p
      where p.id = auth.uid() and p.is_active and p.is_logistics_contact)
  ), false)
$$;
revoke all on function public.can_manage_logistics_requests(uuid) from public, anon;
grant execute on function public.can_manage_logistics_requests(uuid) to authenticated;

create table public.logistics_requests (
  id uuid primary key default gen_random_uuid(),
  headquarters_id uuid not null references public.headquarters(id) on delete restrict,
  created_by uuid not null default auth.uid() references public.profiles(id) on delete restrict,
  material text not null check (char_length(trim(material)) between 2 and 160),
  quantity numeric not null check (
    quantity > 0 and quantity <= 999999999.999 and quantity = round(quantity, 3)
  ),
  unit text not null default 'unidades' check (char_length(trim(unit)) between 1 and 40),
  notes text not null default '' check (char_length(notes) <= 2000),
  status text not null default 'pending'
    check (status in ('pending', 'accepted', 'preparing', 'completed', 'cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index logistics_requests_site_status_idx
  on public.logistics_requests(headquarters_id, status, created_at desc);
create index logistics_requests_author_idx
  on public.logistics_requests(created_by, created_at desc);

create table public.logistics_request_history (
  id uuid primary key default gen_random_uuid(),
  request_id uuid not null references public.logistics_requests(id) on delete restrict,
  actor_id uuid not null references public.profiles(id) on delete restrict,
  from_status text check (from_status in ('pending', 'accepted', 'preparing', 'completed', 'cancelled')),
  to_status text not null check (to_status in ('pending', 'accepted', 'preparing', 'completed', 'cancelled')),
  created_at timestamptz not null default now()
);
create index logistics_request_history_request_idx
  on public.logistics_request_history(request_id, created_at);

alter table public.logistics_requests enable row level security;
alter table public.logistics_request_history enable row level security;

create policy logistics_requests_read on public.logistics_requests
for select to authenticated using (
  public.can_manage_logistics_requests(headquarters_id)
  or (public.user_role() is not null and created_by = auth.uid()
    and headquarters_id = public.user_headquarters_id())
);
create policy logistics_requests_create on public.logistics_requests
for insert to authenticated with check (
  public.user_role() is not null and created_by = auth.uid() and status = 'pending'
  and (public.user_role() = 'admin' or headquarters_id = public.user_headquarters_id())
  and exists (select 1 from public.headquarters h where h.id = headquarters_id and h.is_active)
);
create policy logistics_requests_manage on public.logistics_requests
for update to authenticated
using (public.can_manage_logistics_requests(headquarters_id))
with check (public.can_manage_logistics_requests(headquarters_id));
create policy logistics_requests_cancel_own on public.logistics_requests
for update to authenticated
using (public.user_role() is not null and created_by = auth.uid()
  and headquarters_id = public.user_headquarters_id() and status = 'pending')
with check (public.user_role() is not null and created_by = auth.uid()
  and headquarters_id = public.user_headquarters_id() and status = 'cancelled');
create policy logistics_request_history_read on public.logistics_request_history
for select to authenticated using (
  exists (select 1 from public.logistics_requests r where r.id = request_id)
);

-- Column grants prevent changing ownership, site, timestamps or request contents.
revoke all on public.logistics_requests, public.logistics_request_history from public, anon, authenticated;
grant select on public.logistics_requests, public.logistics_request_history to authenticated;
grant insert (headquarters_id, material, quantity, unit, notes) on public.logistics_requests to authenticated;
grant update (status) on public.logistics_requests to authenticated;

create function public.guard_logistics_request_status()
returns trigger language plpgsql set search_path = public as $$
begin
  if new.status is not distinct from old.status then return new; end if;
  if not (
    (old.status = 'pending' and new.status in ('accepted', 'cancelled')) or
    (old.status = 'accepted' and new.status in ('preparing', 'cancelled')) or
    (old.status = 'preparing' and new.status in ('completed', 'cancelled'))
  ) or new.status is null then
    raise exception 'Transicion de solicitud no permitida' using errcode = '23514';
  end if;
  new.updated_at = clock_timestamp();
  return new;
end $$;
create trigger guard_logistics_request_status before update on public.logistics_requests
for each row execute function public.guard_logistics_request_status();

-- History is written atomically by the database, never by a client or mail job.
create function public.record_logistics_request_history()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if tg_op = 'INSERT' then
    insert into public.logistics_request_history(request_id, actor_id, from_status, to_status)
    values (new.id, auth.uid(), null, new.status);
  elsif new.status is distinct from old.status then
    insert into public.logistics_request_history(request_id, actor_id, from_status, to_status)
    values (new.id, auth.uid(), old.status, new.status);
  end if;
  return new;
end $$;
create trigger record_logistics_request_history after insert or update on public.logistics_requests
for each row execute function public.record_logistics_request_history();
revoke all on function public.guard_logistics_request_status() from public, anon, authenticated;
revoke all on function public.record_logistics_request_history() from public, anon, authenticated;

$iae_ddl$;
insert into iae_internal.migrations(version) values('202609140002_logistics_requests.sql');
end if;
end $iae_apply$;

do $iae_apply$ begin
if not exists(select 1 from iae_internal.migrations where version='202609140003_documents_and_validation.sql') then
execute $iae_ddl$alter table public.inventory_attachments add column if not exists storage_path text;
alter table public.inventory_attachments alter column url drop not null;
alter table public.inventory_attachments drop constraint if exists attachment_source;
alter table public.inventory_attachments add constraint attachment_source check ((url is null) <> (storage_path is null));
create unique index if not exists attachment_storage_path_idx on public.inventory_attachments(storage_path);

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('inventory-documents','inventory-documents',false,4194304,array['application/pdf','image/jpeg','image/png'])
on conflict(id) do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
drop policy if exists "Admins upload inventory documents" on storage.objects;
create policy "Admins upload inventory documents" on storage.objects for insert to authenticated
with check(bucket_id='inventory-documents' and public.user_role()='admin');
drop policy if exists "Admins delete inventory documents" on storage.objects;
create policy "Admins delete inventory documents" on storage.objects for delete to authenticated
using(bucket_id='inventory-documents' and public.user_role()='admin');
drop policy if exists "Read visible inventory documents" on storage.objects;
create policy "Read visible inventory documents" on storage.objects for select to authenticated
using(bucket_id='inventory-documents' and exists(select 1 from public.inventory_attachments a where a.storage_path=name));

create or replace function public.validate_inventory_fields() returns trigger
language plpgsql security definer set search_path=public as $$
declare f record; values_json jsonb; val text;
begin
  if new.template_id is null then return new; end if;
  if new.category is distinct from (select category_code from public.inventory_templates where id=new.template_id) then raise exception 'Categoria y plantilla no coinciden'; end if;
  values_json=coalesce(new.technical_specs,'{}'::jsonb) || jsonb_build_object(
    'item_name',new.name,'name',new.name,'description',new.description,'subtype',new.subtype,'sku',new.sku,'serial_number',new.serial_number,
    'current_stock',new.current_stock,'minimum_stock',new.minimum_stock,'unit',new.unit,'expiration_date',new.expiration_date,
    'maintenance_due_at',new.maintenance_due_at,'location_id',new.location_id,'lot_code',new.lot_code,'is_consumable',new.is_consumable);
  for f in select d.field_key,d.field_type,d.options,a.is_required from public.inventory_template_fields a join public.inventory_fields d on d.id=a.field_id where a.template_id=new.template_id loop
    val=values_json->>f.field_key;
    if f.is_required and f.field_type<>'boolean' and (val is null or trim(val)='') then raise exception 'Falta campo obligatorio: %',f.field_key; end if;
    if val is null or val='' then continue; end if;
    if f.field_type='number' and val !~ '^-?[0-9]+(\.[0-9]+)?$' then raise exception 'Numero invalido: %',f.field_key; end if;
    if f.field_type='date' then perform val::date; end if;
    if f.field_type='boolean' and val not in ('true','false') then raise exception 'Booleano invalido: %',f.field_key; end if;
    if f.field_type='select' and not (f.options ? val) then raise exception 'Opcion invalida: %',f.field_key; end if;
  end loop;
  return new;
end $$;
drop trigger if exists validate_inventory_fields on public.inventory_items;
create trigger validate_inventory_fields before insert or update of technical_specs,template_id on public.inventory_items for each row execute function public.validate_inventory_fields();

create or replace function public.update_catalog_field(p_id uuid,p_key text,p_label text,p_type text,p_options jsonb)
returns void language plpgsql security definer set search_path=public as $$
begin
  if public.user_role() is distinct from 'admin' then raise exception 'Sin permiso'; end if;
  update public.inventory_fields set field_key=p_key,label=p_label,field_type=p_type,options=p_options where id=p_id;
  if not found then raise exception 'Campo no encontrado'; end if;
  update public.inventory_template_fields set field_key=p_key,label=p_label,field_type=p_type,options=p_options where field_id=p_id;
end $$;
revoke all on function public.update_catalog_field(uuid,text,text,text,jsonb) from public;
grant execute on function public.update_catalog_field(uuid,text,text,text,jsonb) to authenticated;

create or replace function public.protect_occupied_container() returns trigger
language plpgsql security definer set search_path=public as $$
begin
  perform pg_advisory_xact_lock(90714001);
  if exists(select 1 from public.inventory_container_items where container_id=old.id) then
    raise exception 'No se puede borrar una caja con articulos';
  end if;
  return old;
end $$;
drop trigger if exists protect_occupied_container on public.inventory_containers;
create trigger protect_occupied_container before delete on public.inventory_containers for each row execute function public.protect_occupied_container();

create or replace function public.sync_template_category() returns trigger
language plpgsql security definer set search_path=public as $$
begin
  if new.category_code is distinct from old.category_code then
    update public.inventory_items set category=new.category_code where template_id=new.id;
  end if;
  return new;
end $$;
drop trigger if exists sync_template_category on public.inventory_templates;
create trigger sync_template_category after update of category_code on public.inventory_templates for each row execute function public.sync_template_category();
$iae_ddl$;
insert into iae_internal.migrations(version) values('202609140003_documents_and_validation.sql');
end if;
end $iae_apply$;

do $iae_apply$ begin
if not exists(select 1 from iae_internal.migrations where version='202609150001_request_articles.sql') then
execute $iae_ddl$alter table public.logistics_requests
  add column if not exists item_id uuid references public.inventory_items(id) on delete restrict;
create index if not exists logistics_requests_item_idx on public.logistics_requests(item_id)
  where item_id is not null;
grant insert (item_id) on public.logistics_requests to authenticated;

-- Store a stable label/unit snapshot, but keep a real link to the source article.
create or replace function public.guard_logistics_request_article()
returns trigger language plpgsql security definer set search_path = public as $$
declare article public.inventory_items%rowtype;
begin
  if tg_op = 'UPDATE' then
    if new.item_id is distinct from old.item_id then
      raise exception 'La referencia de una solicitud no se puede cambiar' using errcode = '23514';
    end if;
    return new;
  end if;
  if new.item_id is null then return new; end if;
  if public.user_role() is null or not coalesce(public.user_role()='admin'
    or new.headquarters_id=public.user_headquarters_id(), false) then
    raise exception 'Articulo no disponible en esta sede' using errcode = '42501';
  end if;
  select * into article from public.inventory_items
    where id=new.item_id and headquarters_id=new.headquarters_id for share;
  if not found then
    raise exception 'Articulo no disponible en esta sede' using errcode = '23514';
  end if;
  new.material=left(article.name,160);
  new.unit=left(coalesce(nullif(trim(article.unit),''),'unidades'),40);
  return new;
end $$;
drop trigger if exists guard_logistics_request_article on public.logistics_requests;
create trigger guard_logistics_request_article before insert or update of item_id on public.logistics_requests
for each row execute function public.guard_logistics_request_article();
revoke all on function public.guard_logistics_request_article() from public, anon, authenticated;

notify pgrst, 'reload schema';
$iae_ddl$;
insert into iae_internal.migrations(version) values('202609150001_request_articles.sql');
end if;
end $iae_apply$;

do $iae_apply$ begin
if not exists(select 1 from iae_internal.migrations where version='202609150002_function_security.sql') then
execute $iae_ddl$-- Both bodies use schema-qualified relations; pg_catalog built-ins remain available.
alter function public.set_updated_at() set search_path = '';
alter function public.protect_field_key() set search_path = '';

-- Supabase may grant EXECUTE to anon/authenticated directly through default ACLs.
-- Revoking only from PUBLIC does not remove those independent grants.
do $permissions$
declare signature text; target regprocedure;
begin
  foreach signature in array array[
    'public.set_updated_at()',
    'public.protect_field_key()',
    'public.handle_new_user()',
    'public.guard_inventory_integrity()',
    'public.protect_last_admin()',
    'public.protect_occupied_container()',
    'public.sync_template_category()',
    'public.validate_inventory_fields()',
    'public.guard_logistics_request_status()',
    'public.record_logistics_request_history()',
    'public.guard_logistics_request_article()'
  ] loop
    target := to_regprocedure(signature);
    -- The article-reference migration may not yet exist when applying this patch alone.
    if target is null and signature = 'public.guard_logistics_request_article()' then continue; end if;
    if target is null then raise exception 'Falta la funcion %. Aplica primero la actualizacion de logistica.', signature; end if;
    execute format('revoke execute on function %s from public, anon, authenticated', target);
  end loop;

  -- Required RPCs and RLS helpers. Their bodies enforce active profiles, roles and sites.
  foreach signature in array array[
    'public.user_role()',
    'public.user_headquarters_id()',
    'public.can_manage_logistics_requests(uuid)',
    'public.create_inventory_record(jsonb,uuid,numeric,text)',
    'public.place_inventory_item(uuid,text,uuid,uuid,numeric,text)',
    'public.record_inventory_movement(uuid,text,numeric,text,uuid)',
    'public.update_inventory_item(uuid,text,text,text,date,date,numeric,text)',
    'public.update_catalog_field(uuid,text,text,text,jsonb)'
  ] loop
    target := to_regprocedure(signature);
    if target is null then raise exception 'Falta la funcion %. Aplica primero la actualizacion de logistica.', signature; end if;
    execute format('revoke execute on function %s from public, anon, authenticated', target);
    execute format('grant execute on function %s to authenticated', target);
  end loop;
end $permissions$;

notify pgrst, 'reload schema';
$iae_ddl$;
insert into iae_internal.migrations(version) values('202609150002_function_security.sql');
end if;
end $iae_apply$;

do $iae_apply$ begin
if not exists(select 1 from iae_internal.migrations where version='202609150003_container_checklists.sql') then
execute $iae_ddl$create table public.container_checklists (
  id uuid primary key,
  container_id uuid not null references public.inventory_containers(id) on delete restrict,
  headquarters_id uuid not null references public.headquarters(id) on delete restrict,
  container_name text not null,
  location_name text not null,
  event_type text not null check(event_type in ('practice','intervention')),
  event_name text not null check(length(trim(event_name)) between 3 and 160),
  event_date date not null,
  team_name text not null default '' check(length(team_name)<=120),
  created_by uuid not null references public.profiles(id),
  created_by_name text not null,
  created_at timestamptz not null default now(),
  status text not null default 'draft' check(status in ('draft','complete','issues','cancelled')),
  closed_by uuid references public.profiles(id),
  closed_by_name text,
  closed_at timestamptz,
  box_returned boolean not null default false,
  summary text not null default '' check(length(summary)<=2000)
);
create unique index container_checklists_one_draft on public.container_checklists(container_id) where status='draft';
create index container_checklists_site_date on public.container_checklists(headquarters_id,created_at desc);
create table public.container_checklist_items (
  id uuid primary key default gen_random_uuid(),
  checklist_id uuid not null references public.container_checklists(id) on delete restrict,
  item_id uuid not null references public.inventory_items(id) on delete restrict,
  item_name text not null,
  unit text not null,
  expected_quantity numeric not null check(expected_quantity>0 and expected_quantity<=99999999999.999 and expected_quantity=round(expected_quantity,3)),
  returned_quantity numeric check(returned_quantity>=0 and returned_quantity<=expected_quantity and returned_quantity=round(returned_quantity,3)),
  result text not null default 'pending' check(result in ('pending','ok','missing','damaged','consumed','misplaced')),
  notes text not null default '' check(length(notes)<=2000),
  checked_by uuid references public.profiles(id),
  checked_by_name text,
  checked_at timestamptz,
  revision integer not null default 0,
  unique(checklist_id,item_id),
  check(result<>'ok' or (returned_quantity is not null and returned_quantity=expected_quantity)),
  check(result in ('pending','ok') or length(trim(notes))>=3)
);
alter table public.container_checklists enable row level security;
alter table public.container_checklist_items enable row level security;
create policy checklists_read on public.container_checklists for select to authenticated
using(public.user_role()='admin' or (public.user_role() is not null and headquarters_id=public.user_headquarters_id()));
create policy checklist_items_read on public.container_checklist_items for select to authenticated
using(exists(select 1 from public.container_checklists c where c.id=checklist_id));
revoke all on public.container_checklists, public.container_checklist_items from public,anon,authenticated;
grant select on public.container_checklists, public.container_checklist_items to authenticated;

create function public.create_container_checklist(p_id uuid,p_container_id uuid,p_event_type text,p_event_name text,p_event_date date,p_team_name text)
returns uuid language plpgsql security definer set search_path='' as $$
declare box public.inventory_containers; existing public.container_checklists; r text; total integer;
begin
  r:=public.user_role();
  if r is null or r not in ('admin','editor','operator','reader','viewer') then raise exception 'Necesitas una cuenta activa'; end if;
  if p_id is null or p_event_type is null or p_event_type not in ('practice','intervention') or p_event_date is null
    or length(trim(coalesce(p_event_name,''))) not between 3 and 160 or length(coalesce(p_team_name,''))>120 then raise exception 'Revisa actividad, fecha y equipo'; end if;
  -- Same lock as stock/placement changes, so the expected contents are one snapshot.
  perform pg_advisory_xact_lock(90714001);
  select * into existing from public.container_checklists where id=p_id;
  if found then
    if existing.created_by=auth.uid() and (r='admin' or existing.headquarters_id=public.user_headquarters_id())
      and existing.container_id=p_container_id and existing.event_type=p_event_type
      and existing.event_name=trim(p_event_name) and existing.event_date=p_event_date and existing.team_name=trim(coalesce(p_team_name,'')) then return existing.id; end if;
    raise exception 'Identificador de revision no disponible';
  end if;
  select * into box from public.inventory_containers where id=p_container_id and is_active;
  if not found or (r<>'admin' and box.headquarters_id is distinct from public.user_headquarters_id()) then raise exception 'Caja no disponible en tu sede'; end if;
  if not exists(select 1 from public.headquarters where id=box.headquarters_id and is_active) then raise exception 'La sede no esta activa'; end if;
  if box.location_id is not null and not exists(select 1 from public.locations where id=box.location_id and headquarters_id=box.headquarters_id) then raise exception 'La ubicacion de la caja no coincide con su sede'; end if;
  if exists(select 1 from public.container_checklists where container_id=box.id and status='draft') then raise exception 'Esta caja ya tiene una revision abierta. Abrela desde Checklists'; end if;
  if exists(select 1 from public.inventory_container_items ci join public.inventory_items i on i.id=ci.item_id
    where ci.container_id=box.id and (i.headquarters_id is distinct from box.headquarters_id or ci.quantity<>i.current_stock or i.location_id is not null)) then
    raise exception 'El contenido de la caja tiene asignaciones inconsistentes. Pide a un administrador que lo revise';
  end if;
  insert into public.container_checklists(id,container_id,headquarters_id,container_name,location_name,event_type,event_name,event_date,team_name,created_by,created_by_name)
    values(p_id,box.id,box.headquarters_id,box.name,coalesce((select name from public.locations where id=box.location_id),'Sin ubicacion asignada'),
      p_event_type,trim(p_event_name),p_event_date,trim(coalesce(p_team_name,'')),auth.uid(),coalesce((select full_name from public.profiles where id=auth.uid()),'Miembro'));
  insert into public.container_checklist_items(checklist_id,item_id,item_name,unit,expected_quantity)
    select p_id,i.id,i.name,coalesce(nullif(trim(i.unit),''),'uds'),ci.quantity
    from public.inventory_container_items ci join public.inventory_items i on i.id=ci.item_id where ci.container_id=box.id;
  get diagnostics total=row_count;
  if total=0 then raise exception 'La caja esta vacia. Asigna su contenido antes de crear el checklist'; end if;
  return p_id;
end $$;

create function public.save_checklist_item(p_line_id uuid,p_revision integer,p_result text,p_quantity numeric,p_notes text)
returns void language plpgsql security definer set search_path='' as $$
declare c public.container_checklists; line public.container_checklist_items; r text;
begin
  r:=public.user_role();
  select * into line from public.container_checklist_items where id=p_line_id;
  select * into c from public.container_checklists where id=line.checklist_id for update;
  if not found or r is null or (r<>'admin' and c.headquarters_id is distinct from public.user_headquarters_id())
    or not (c.created_by=auth.uid() or public.can_manage_logistics_requests(c.headquarters_id)) then raise exception 'No puedes completar esta revision'; end if;
  if c.status<>'draft' then raise exception 'La revision ya esta cerrada'; end if;
  select * into line from public.container_checklist_items where id=p_line_id for update;
  if p_revision is null or line.revision<>p_revision then raise exception 'El articulo ha cambiado. Recarga antes de guardar' using errcode='40001'; end if;
  if p_result is null or p_result not in ('pending','ok','missing','damaged','consumed','misplaced')
    or length(coalesce(p_notes,''))>2000 then raise exception 'Resultado no valido'; end if;
  if p_result='ok' then p_quantity:=line.expected_quantity;
  elsif p_result='pending' then p_quantity:=null;
  elsif p_quantity is null or p_quantity<0 or p_quantity>line.expected_quantity or p_quantity<>round(p_quantity,3)
    or length(trim(coalesce(p_notes,'')))<3 then raise exception 'Indica cantidad comprobada y una nota para la incidencia'; end if;
  if p_result in ('missing','consumed') and p_quantity>=line.expected_quantity then raise exception 'La cantidad devuelta debe ser menor que la esperada'; end if;
  update public.container_checklist_items set result=p_result,returned_quantity=p_quantity,notes=trim(coalesce(p_notes,'')),
    checked_by=case when p_result='pending' then null else auth.uid() end,
    checked_by_name=case when p_result='pending' then null else coalesce((select full_name from public.profiles where id=auth.uid()),'Miembro') end,
    checked_at=case when p_result='pending' then null else clock_timestamp() end,revision=revision+1 where id=p_line_id;
end $$;

create function public.close_container_checklist(p_id uuid,p_box_returned boolean,p_summary text,p_cancel boolean default false)
returns text language plpgsql security definer set search_path='' as $$
declare c public.container_checklists; r text; final_status text;
begin
  r:=public.user_role();
  select * into c from public.container_checklists where id=p_id for update;
  if not found or r is null or (r<>'admin' and c.headquarters_id is distinct from public.user_headquarters_id())
    or not (c.created_by=auth.uid() or public.can_manage_logistics_requests(c.headquarters_id)) then raise exception 'No puedes cerrar esta revision'; end if;
  if c.status<>'draft' then raise exception 'La revision ya esta cerrada'; end if;
  if p_cancel is null or length(coalesce(p_summary,''))>2000 then raise exception 'Resumen no valido'; end if;
  if p_cancel then
    if length(trim(coalesce(p_summary,'')))<3 then raise exception 'Indica el motivo de cancelacion'; end if;
    final_status:='cancelled';
  else
    if exists(select 1 from public.container_checklist_items where checklist_id=c.id and result='pending') then raise exception 'Quedan articulos pendientes de comprobar'; end if;
    if not exists(select 1 from public.container_checklist_items where checklist_id=c.id) then raise exception 'La revision no tiene articulos'; end if;
    if not coalesce(p_box_returned,false) and length(trim(coalesce(p_summary,'')))<3 then raise exception 'Indica donde queda la caja si no ha vuelto a su ubicacion'; end if;
    final_status:=case when not coalesce(p_box_returned,false) or exists(select 1 from public.container_checklist_items where checklist_id=c.id and result<>'ok') then 'issues' else 'complete' end;
  end if;
  update public.container_checklists set status=final_status,closed_by=auth.uid(),closed_by_name=coalesce((select full_name from public.profiles where id=auth.uid()),'Miembro'),closed_at=clock_timestamp(),
    box_returned=case when p_cancel then false else coalesce(p_box_returned,false) end,summary=trim(coalesce(p_summary,'')) where id=c.id;
  return final_status;
end $$;
revoke execute on function public.create_container_checklist(uuid,uuid,text,text,date,text),public.save_checklist_item(uuid,integer,text,numeric,text),public.close_container_checklist(uuid,boolean,text,boolean) from public,anon,authenticated;
grant execute on function public.create_container_checklist(uuid,uuid,text,text,date,text),public.save_checklist_item(uuid,integer,text,numeric,text),public.close_container_checklist(uuid,boolean,text,boolean) to authenticated;
notify pgrst,'reload schema';
$iae_ddl$;
insert into iae_internal.migrations(version) values('202609150003_container_checklists.sql');
end if;
end $iae_apply$;

do $iae_apply$ begin
if not exists(select 1 from iae_internal.migrations where version='202609160001_distributed_stock.sql') then
execute $iae_ddl$-- Keep the old item and box totals as read-only projections for existing screens.
create table public.inventory_stock_lots (
  id uuid primary key default gen_random_uuid(),
  item_id uuid not null references public.inventory_items(id) on delete restrict,
  code text not null check(length(trim(code)) between 1 and 120),
  expiration_date date,
  created_at timestamptz not null default now(),
  unique(item_id,code), unique(id,item_id)
);
create table public.inventory_stock_positions (
  id uuid primary key default gen_random_uuid(),
  item_id uuid not null references public.inventory_items(id) on delete restrict,
  lot_id uuid not null,
  location_id uuid references public.locations(id) on delete restrict,
  container_id uuid references public.inventory_containers(id) on delete restrict,
  notes text not null default '',
  quantity numeric not null check(quantity>=0 and quantity<=99999999999.999 and quantity=round(quantity,3)),
  foreign key(lot_id,item_id) references public.inventory_stock_lots(id,item_id),
  check(location_id is null or container_id is null),
  unique nulls not distinct(lot_id,location_id,container_id)
);
create index stock_positions_item on public.inventory_stock_positions(item_id);
create index stock_positions_box on public.inventory_stock_positions(container_id);
create index stock_positions_location on public.inventory_stock_positions(location_id);
create table public.inventory_stock_events (
  request_id uuid primary key,
  item_id uuid not null references public.inventory_items(id),
  actor_id uuid not null references public.profiles(id),
  payload jsonb not null,
  balance_after numeric not null,
  created_at timestamptz not null default now()
);

do $$ begin
  if exists(select 1 from public.inventory_container_items c join public.inventory_items i on i.id=c.item_id
    where c.quantity<>i.current_stock or i.location_id is not null) then
    raise exception 'Hay asignaciones antiguas inconsistentes. Revisa cajas y cantidades antes de migrar';
  end if;
  if exists(select 1 from public.inventory_items where nullif(trim(serial_number),'') is not null and current_stock not in (0,1)) then
    raise exception 'Una herramienta con numero de serie tiene una cantidad distinta de 0 o 1. Corrige su stock antes de migrar';
  end if;
end $$;
insert into public.inventory_stock_lots(item_id,code,expiration_date)
select id,coalesce(nullif(trim(lot_code),''),'Inicial'),expiration_date from public.inventory_items;
insert into public.inventory_stock_positions(item_id,lot_id,location_id,container_id,quantity,notes)
select i.id,l.id,i.location_id,c.container_id,i.current_stock,coalesce(c.notes,'') from public.inventory_items i
join public.inventory_stock_lots l on l.item_id=i.id
left join public.inventory_container_items c on c.item_id=i.id;
drop index if exists public.inventory_container_items_one_container_per_item_idx;

alter table public.inventory_stock_lots enable row level security;
alter table public.inventory_stock_positions enable row level security;
alter table public.inventory_stock_events enable row level security;
create policy stock_lots_read on public.inventory_stock_lots for select to authenticated
using(exists(select 1 from public.inventory_items i where i.id=item_id));
create policy stock_positions_read on public.inventory_stock_positions for select to authenticated
using(exists(select 1 from public.inventory_items i where i.id=item_id));
create policy stock_events_read on public.inventory_stock_events for select to authenticated
using(exists(select 1 from public.inventory_items i where i.id=item_id));
revoke all on public.inventory_stock_lots,public.inventory_stock_positions,public.inventory_stock_events from public,anon,authenticated;
grant select on public.inventory_stock_lots,public.inventory_stock_positions,public.inventory_stock_events to authenticated;
revoke insert,update,delete on public.inventory_items,public.inventory_container_items from public,anon,authenticated;

create or replace function public.guard_inventory_integrity() returns trigger
language plpgsql security definer set search_path='' as $$
declare h uuid; other_h uuid;
begin
  perform pg_advisory_xact_lock(90714001);
  if tg_table_name='locations' then
    if new.headquarters_id is null then raise exception 'La ubicacion necesita sede'; end if;
    if new.parent_location_id is not null then
      select headquarters_id into h from public.locations where id=new.parent_location_id;
      if h is distinct from new.headquarters_id then raise exception 'La ubicacion padre debe ser de la misma sede'; end if;
      if exists(with recursive ancestors as (
        select id,parent_location_id from public.locations where id=new.parent_location_id
        union select l.id,l.parent_location_id from public.locations l join ancestors a on l.id=a.parent_location_id
      ) select 1 from ancestors where id=new.id) then raise exception 'La jerarquia de ubicaciones contiene un ciclo'; end if;
    end if;
    if tg_op='UPDATE' and old.headquarters_id is distinct from new.headquarters_id and (
      exists(select 1 from public.inventory_stock_positions where location_id=new.id) or
      exists(select 1 from public.inventory_containers where location_id=new.id) or
      exists(select 1 from public.locations where parent_location_id=new.id)
    ) then raise exception 'La ubicacion tiene existencias o historial asociado'; end if;
  elsif tg_table_name='inventory_containers' then
    if new.location_id is not null then
      select headquarters_id into h from public.locations where id=new.location_id;
      if h is distinct from new.headquarters_id then raise exception 'La caja y su ubicacion deben pertenecer a la misma sede'; end if;
    end if;
    if tg_op='UPDATE' and old.headquarters_id is distinct from new.headquarters_id and
      exists(select 1 from public.inventory_stock_positions where container_id=new.id) then raise exception 'La caja tiene existencias o historial asociado'; end if;
  elsif tg_table_name='inventory_items' then
    if new.headquarters_id is null then raise exception 'El articulo necesita sede'; end if;
    if new.location_id is not null then
      select headquarters_id into h from public.locations where id=new.location_id;
      if h is distinct from new.headquarters_id then raise exception 'Articulo y ubicacion deben ser de la misma sede'; end if;
    end if;
    if tg_op='UPDATE' and old.headquarters_id is distinct from new.headquarters_id and
      exists(select 1 from public.inventory_stock_lots where item_id=new.id) then raise exception 'El inventario y su historial pertenecen a su sede'; end if;
    if nullif(trim(new.serial_number),'') is not null and new.current_stock not in (0,1) then raise exception 'Una herramienta identificada por serie admite 0 o 1 unidades'; end if;
  elsif tg_table_name='inventory_container_items' then
    select headquarters_id into h from public.inventory_items where id=new.item_id;
    select headquarters_id into other_h from public.inventory_containers where id=new.container_id;
    if h is null or h is distinct from other_h then raise exception 'Caja y articulo deben pertenecer a la misma sede'; end if;
  elsif tg_table_name='inventory_item_relations' then
    select headquarters_id into h from public.inventory_items where id=new.source_item_id;
    select headquarters_id into other_h from public.inventory_items where id=new.target_item_id;
    if new.source_item_id=new.target_item_id or h is null or h is distinct from other_h then raise exception 'Relacion invalida o entre sedes diferentes'; end if;
  end if;
  return new;
end $$;

create function public.sync_inventory_stock(p_item_id uuid) returns void
language plpgsql security definer set search_path='' as $$
declare total numeric; direct uuid; expiry date;
begin
  select coalesce(sum(quantity),0) into total from public.inventory_stock_positions where item_id=p_item_id;
  if (select count(*) from public.inventory_stock_positions where item_id=p_item_id and quantity>0)=1 then
    select location_id into direct from public.inventory_stock_positions where item_id=p_item_id and quantity>0;
  end if;
  select min(l.expiration_date) into expiry from public.inventory_stock_lots l
    where l.item_id=p_item_id and exists(select 1 from public.inventory_stock_positions s where s.lot_id=l.id and s.quantity>0);
  delete from public.inventory_container_items where item_id=p_item_id;
  update public.inventory_items set current_stock=total,location_id=direct,expiration_date=expiry,
    status=case when expiry<current_date then 'expired' when minimum_stock is not null and total<=minimum_stock then 'low' else 'ok' end where id=p_item_id;
  insert into public.inventory_container_items(item_id,container_id,quantity)
    select p_item_id,container_id,sum(quantity) from public.inventory_stock_positions
    where item_id=p_item_id and container_id is not null group by container_id having sum(quantity)>0;
end $$;

create function public.manage_inventory_stock(p_request_id uuid,p_item_id uuid,p_action text,p_source_id uuid,p_lot_id uuid,
  p_location_id uuid,p_container_id uuid,p_quantity numeric,p_notes text,p_lot_code text default null,p_expiration_date date default null,p_expected_quantity numeric default null)
returns numeric language plpgsql security definer set search_path='' as $$
declare i public.inventory_items; src public.inventory_stock_positions; dest uuid; lot uuid; total numeric; payload jsonb; previous public.inventory_stock_events; previous_lot jsonb;
begin
  if public.user_role() is distinct from 'admin' then raise exception 'Solo administracion puede modificar existencias'; end if;
  if p_request_id is null or p_action is null or p_action not in ('in','out','adjustment','transfer','new_lot','edit_lot')
    or p_quantity is null or p_quantity<0 or p_quantity>99999999999.999 or p_quantity<>round(p_quantity,3)
    or (p_action in ('in','out','transfer') and p_quantity=0)
    or length(trim(coalesce(p_notes,''))) not between 3 and 2000 then raise exception 'Revisa operacion, cantidad y motivo'; end if;
  payload=jsonb_build_object('action',p_action,'source',p_source_id,'lot',p_lot_id,'location',p_location_id,'container',p_container_id,
    'quantity',p_quantity,'notes',p_notes,'code',p_lot_code,'expiry',p_expiration_date,'expected_quantity',p_expected_quantity);
  perform pg_advisory_xact_lock(90714001);
  select * into previous from public.inventory_stock_events where request_id=p_request_id;
  if found then
    if previous.item_id is distinct from p_item_id or previous.actor_id<>auth.uid() or previous.payload<>payload then raise exception 'Identificador reutilizado con datos distintos'; end if;
    return previous.balance_after;
  end if;
  select * into i from public.inventory_items where id=p_item_id for update;
  if not found then raise exception 'Articulo no encontrado'; end if;
  if p_location_id is not null and p_container_id is not null then raise exception 'Elige caja o ubicacion, no ambas'; end if;
  if p_action in ('in','transfer','new_lot') then
    if p_location_id is not null and not exists(select 1 from public.locations where id=p_location_id and headquarters_id=i.headquarters_id and is_active) then raise exception 'Ubicacion no disponible en esta sede'; end if;
    if p_container_id is not null and not exists(select 1 from public.inventory_containers where id=p_container_id and headquarters_id=i.headquarters_id and is_active) then raise exception 'Caja no disponible en esta sede'; end if;
    if not exists(select 1 from public.headquarters where id=i.headquarters_id and is_active) then raise exception 'Sede inactiva'; end if;
  end if;
  if p_action in ('transfer','out','adjustment') then
    select * into src from public.inventory_stock_positions where id=p_source_id and item_id=i.id for update;
    if not found then raise exception 'Existencia de origen no encontrada'; end if;
    if p_expected_quantity is not null and p_expected_quantity<>src.quantity then raise exception 'La cantidad de origen ha cambiado. Recarga antes de guardar'; end if;
    lot=src.lot_id;
    if p_action<>'adjustment' and p_quantity>src.quantity then raise exception 'Stock insuficiente en el origen'; end if;
  elsif p_action='new_lot' then
    if length(trim(coalesce(p_lot_code,''))) not between 1 and 120 then raise exception 'Indica el codigo del lote'; end if;
    insert into public.inventory_stock_lots(item_id,code,expiration_date) values(i.id,trim(p_lot_code),p_expiration_date) returning id into lot;
  else
    select id into lot from public.inventory_stock_lots where id=p_lot_id and item_id=i.id;
    if not found then raise exception 'Lote no encontrado para este articulo'; end if;
  end if;
  if p_action='edit_lot' then
    if length(trim(coalesce(p_lot_code,''))) not between 1 and 120 then raise exception 'Indica el codigo del lote'; end if;
    select to_jsonb(l) into previous_lot from public.inventory_stock_lots l where id=lot;
    update public.inventory_stock_lots set code=trim(p_lot_code),expiration_date=p_expiration_date where id=lot;
  else
    if p_action in ('in','transfer','new_lot') then
      if p_action='transfer' and src.location_id is not distinct from p_location_id and src.container_id is not distinct from p_container_id then raise exception 'Origen y destino son iguales'; end if;
      insert into public.inventory_stock_positions(item_id,lot_id,location_id,container_id,quantity)
        values(i.id,lot,p_location_id,p_container_id,0) on conflict(lot_id,location_id,container_id) do nothing;
      select id into dest from public.inventory_stock_positions where lot_id=lot and location_id is not distinct from p_location_id and container_id is not distinct from p_container_id;
      update public.inventory_stock_positions set quantity=quantity+p_quantity where id=dest;
    end if;
    if p_action in ('out','transfer','adjustment') then
      update public.inventory_stock_positions set quantity=case when p_action='adjustment' then p_quantity else quantity-p_quantity end where id=src.id;
    end if;
  end if;
  if nullif(trim(i.serial_number),'') is not null and exists(select 1 from public.inventory_stock_positions
    where item_id=i.id and quantity not in (0,1)) then raise exception 'No puedes dividir una herramienta identificada por serie'; end if;
  perform public.sync_inventory_stock(i.id);
  select current_stock into total from public.inventory_items where id=i.id;
  insert into public.inventory_stock_events(request_id,item_id,actor_id,payload,balance_after) values(p_request_id,i.id,auth.uid(),payload,total);
  insert into public.inventory_item_history(item_id,actor_id,event_type,details)
    values(i.id,auth.uid(),'stock_'||p_action,payload||jsonb_build_object('lot_id',lot,'lot_before',previous_lot,'destination_id',dest,'source_before',to_jsonb(src),'balance_after',total,'request_id',p_request_id));
  if p_action in ('in','out','adjustment','new_lot') then
    insert into public.inventory_movements(item_id,movement_type,quantity,notes,created_by,balance_after,request_id)
      values(i.id,case when p_action='new_lot' then 'in' else p_action end,p_quantity,p_notes,auth.uid(),total,p_request_id);
  end if;
  return total;
end $$;

-- Old clients cannot overwrite a distribution by moving or recounting its total.
create or replace function public.place_inventory_item(p_item_id uuid,p_type text,p_location_id uuid default null,p_container_id uuid default null,p_quantity numeric default 1,p_notes text default null)
returns void language plpgsql security definer set search_path='' as $$
begin raise exception 'Usa Existencias y ubicaciones para trasladar cantidades desde un origen concreto'; end $$;
create or replace function public.record_inventory_movement(p_item_id uuid,p_type text,p_quantity numeric,p_notes text,p_request_id uuid)
returns numeric language plpgsql security definer set search_path='' as $$
declare s public.inventory_stock_positions;
begin
  if public.user_role() is distinct from 'admin' then raise exception 'Solo administracion puede modificar existencias'; end if;
  perform pg_advisory_xact_lock(90714001);
  if (select count(*) from public.inventory_stock_positions where item_id=p_item_id)<>1 then raise exception 'Elige el lote y la ubicacion concreta en Existencias y ubicaciones'; end if;
  select * into s from public.inventory_stock_positions where item_id=p_item_id;
  return public.manage_inventory_stock(p_request_id,p_item_id,p_type,s.id,s.lot_id,s.location_id,s.container_id,p_quantity,p_notes);
end $$;

alter function public.create_inventory_record(jsonb,uuid,numeric,text) rename to create_inventory_record_before_distribution;
create function public.create_inventory_record(p_record jsonb,p_container_id uuid default null,p_quantity numeric default null,p_notes text default null)
returns uuid language plpgsql security definer set search_path='' as $$
declare item uuid; lot uuid; stock numeric;
begin
  if public.user_role() is null or public.user_role() not in ('admin','editor','operator') or
    (public.user_role()<>'admin' and (p_record->>'headquarters_id')::uuid is distinct from public.user_headquarters_id()) then raise exception 'No tienes permiso para crear en esta sede'; end if;
  stock=coalesce((p_record->>'current_stock')::numeric,0);
  if stock<0 or stock>99999999999.999 or stock<>round(stock,3) then raise exception 'Cantidad inicial no valida'; end if;
  if nullif(p_record->>'location_id','') is not null and not exists(select 1 from public.locations
    where id=(p_record->>'location_id')::uuid and headquarters_id=(p_record->>'headquarters_id')::uuid and is_active) then raise exception 'Ubicacion no disponible en esta sede'; end if;
  if p_container_id is not null and (nullif(p_record->>'location_id','') is not null or not exists(
    select 1 from public.inventory_containers where id=p_container_id and headquarters_id=(p_record->>'headquarters_id')::uuid and is_active
  )) then raise exception 'Caja no disponible o destino doble'; end if;
  item=public.create_inventory_record_before_distribution(p_record,null,p_quantity,p_notes);
  insert into public.inventory_stock_lots(item_id,code,expiration_date)
    values(item,coalesce(nullif(trim(p_record->>'lot_code'),''),'Inicial'),(p_record->>'expiration_date')::date) returning id into lot;
  insert into public.inventory_stock_positions(item_id,lot_id,location_id,container_id,quantity,notes)
    select item,lot,location_id,p_container_id,current_stock,coalesce(p_notes,'') from public.inventory_items where id=item;
  perform public.sync_inventory_stock(item);
  return item;
end $$;
alter function public.update_inventory_item(uuid,text,text,text,date,date,numeric,text) rename to update_inventory_item_before_distribution;
create function public.update_inventory_item(p_item_id uuid,p_name text,p_description text,p_status text,p_maintenance_due_at date,p_expiration_date date,p_minimum_stock numeric,p_notes text)
returns void language plpgsql security definer set search_path='' as $$
begin
  if public.user_role() is distinct from 'admin' then raise exception 'Solo administracion puede editar articulos'; end if;
  perform pg_advisory_xact_lock(90714001);
  if p_expiration_date is distinct from (select expiration_date from public.inventory_items where id=p_item_id) then
    if (select count(*) from public.inventory_stock_lots where item_id=p_item_id)<>1 then raise exception 'Edita la caducidad desde el lote concreto'; end if;
    update public.inventory_stock_lots set expiration_date=p_expiration_date where item_id=p_item_id;
  end if;
  perform public.update_inventory_item_before_distribution(p_item_id,p_name,p_description,p_status,p_maintenance_due_at,p_expiration_date,p_minimum_stock,p_notes);
  perform public.sync_inventory_stock(p_item_id);
end $$;

-- Preserve old checklist rows; new rows snapshot each lot separately.
alter table public.container_checklist_items drop constraint container_checklist_items_checklist_id_item_id_key;
alter table public.container_checklist_items add column lot_id uuid references public.inventory_stock_lots(id);
alter table public.container_checklist_items add column lot_code text;
alter table public.container_checklist_items add column expiration_date date;
create unique index checklist_item_lot on public.container_checklist_items(checklist_id,item_id,lot_id);

create or replace function public.create_container_checklist(p_id uuid,p_container_id uuid,p_event_type text,p_event_name text,p_event_date date,p_team_name text)
returns uuid language plpgsql security definer set search_path='' as $$
declare box public.inventory_containers; existing public.container_checklists; r text; total integer;
begin
  r:=public.user_role();
  if r is null or r not in ('admin','editor','operator','reader','viewer') then raise exception 'Necesitas una cuenta activa'; end if;
  if p_id is null or p_event_type is null or p_event_type not in ('practice','intervention') or p_event_date is null
    or length(trim(coalesce(p_event_name,''))) not between 3 and 160 or length(coalesce(p_team_name,''))>120 then raise exception 'Revisa actividad, fecha y equipo'; end if;
  -- Same lock as stock/placement changes, so the expected contents are one snapshot.
  perform pg_advisory_xact_lock(90714001);
  select * into existing from public.container_checklists where id=p_id;
  if found then
    if existing.created_by=auth.uid() and (r='admin' or existing.headquarters_id=public.user_headquarters_id())
      and existing.container_id=p_container_id and existing.event_type=p_event_type
      and existing.event_name=trim(p_event_name) and existing.event_date=p_event_date and existing.team_name=trim(coalesce(p_team_name,'')) then return existing.id; end if;
    raise exception 'Identificador de revision no disponible';
  end if;
  select * into box from public.inventory_containers where id=p_container_id and is_active;
  if not found or (r<>'admin' and box.headquarters_id is distinct from public.user_headquarters_id()) then raise exception 'Caja no disponible en tu sede'; end if;
  if not exists(select 1 from public.headquarters where id=box.headquarters_id and is_active) then raise exception 'La sede no esta activa'; end if;
  if box.location_id is not null and not exists(select 1 from public.locations where id=box.location_id and headquarters_id=box.headquarters_id) then raise exception 'La ubicacion de la caja no coincide con su sede'; end if;
  if exists(select 1 from public.container_checklists where container_id=box.id and status='draft') then raise exception 'Esta caja ya tiene una revision abierta. Abrela desde Checklists'; end if;
  insert into public.container_checklists(id,container_id,headquarters_id,container_name,location_name,event_type,event_name,event_date,team_name,created_by,created_by_name)
    values(p_id,box.id,box.headquarters_id,box.name,coalesce((select name from public.locations where id=box.location_id),'Sin ubicacion asignada'),
      p_event_type,trim(p_event_name),p_event_date,trim(coalesce(p_team_name,'')),auth.uid(),coalesce((select full_name from public.profiles where id=auth.uid()),'Miembro'));
  insert into public.container_checklist_items(checklist_id,item_id,item_name,unit,expected_quantity,lot_id,lot_code,expiration_date)
    select p_id,i.id,i.name,coalesce(nullif(trim(i.unit),''),'uds'),s.quantity,l.id,l.code,l.expiration_date
    from public.inventory_stock_positions s join public.inventory_items i on i.id=s.item_id
    join public.inventory_stock_lots l on l.id=s.lot_id where s.container_id=box.id and s.quantity>0;
  get diagnostics total=row_count;
  if total=0 then raise exception 'La caja esta vacia. Asigna su contenido antes de crear el checklist'; end if;
  return p_id;
end $$;


revoke execute on function public.sync_inventory_stock(uuid),public.create_inventory_record_before_distribution(jsonb,uuid,numeric,text),
  public.update_inventory_item_before_distribution(uuid,text,text,text,date,date,numeric,text) from public,anon,authenticated;
revoke execute on function public.manage_inventory_stock(uuid,uuid,text,uuid,uuid,uuid,uuid,numeric,text,text,date,numeric),
  public.create_inventory_record(jsonb,uuid,numeric,text),public.update_inventory_item(uuid,text,text,text,date,date,numeric,text) from public,anon,authenticated;
grant execute on function public.manage_inventory_stock(uuid,uuid,text,uuid,uuid,uuid,uuid,numeric,text,text,date,numeric),
  public.create_inventory_record(jsonb,uuid,numeric,text),public.update_inventory_item(uuid,text,text,text,date,date,numeric,text) to authenticated;
notify pgrst,'reload schema';
$iae_ddl$;
insert into iae_internal.migrations(version) values('202609160001_distributed_stock.sql');
end if;
end $iae_apply$;

do $iae_apply$ begin
if not exists(select 1 from iae_internal.migrations where version='202609170001_barcode_receiving.sql') then
execute $iae_ddl$create table public.inventory_variants (
  id uuid primary key default gen_random_uuid(),
  item_id uuid not null references public.inventory_items(id),
  brand text not null check(length(trim(brand)) between 1 and 80),
  model text not null default '' check(length(model)<=80),
  unique(item_id,brand,model), unique(id,item_id)
);
create table public.inventory_barcodes (
  id uuid primary key default gen_random_uuid(),
  headquarters_id uuid not null references public.headquarters(id),
  item_id uuid not null references public.inventory_items(id),
  variant_id uuid not null,
  code text not null check(code ~ '^[!-~]{1,128}$'),
  units_per_pack numeric not null check(units_per_pack>0 and units_per_pack<=999999 and units_per_pack=round(units_per_pack,3)),
  foreign key(variant_id,item_id) references public.inventory_variants(id,item_id),
  unique(headquarters_id,code)
);
alter table public.inventory_stock_lots add column variant_id uuid;
alter table public.inventory_stock_lots add foreign key(variant_id,item_id) references public.inventory_variants(id,item_id);
create table public.inventory_receipts (
  id uuid primary key,
  item_id uuid not null references public.inventory_items(id),
  actor_id uuid not null references public.profiles(id),
  payload jsonb not null,
  balance_after numeric not null,
  created_at timestamptz not null default now()
);
create table public.barcode_catalog_requests (
  id uuid primary key,
  actor_id uuid not null references public.profiles(id),
  payload jsonb not null,
  request_id uuid not null references public.logistics_requests(id)
);
create table public.inventory_creation_requests (
  id uuid primary key,
  actor_id uuid not null references public.profiles(id),
  payload jsonb not null,
  item_id uuid not null references public.inventory_items(id)
);
alter table public.inventory_variants enable row level security;
alter table public.inventory_barcodes enable row level security;
alter table public.inventory_receipts enable row level security;
alter table public.barcode_catalog_requests enable row level security;
alter table public.inventory_creation_requests enable row level security;
create policy variants_read on public.inventory_variants for select to authenticated using(exists(select 1 from public.inventory_items i where i.id=item_id));
create policy barcodes_read on public.inventory_barcodes for select to authenticated using(exists(select 1 from public.inventory_items i where i.id=item_id));
create policy receipts_read on public.inventory_receipts for select to authenticated using(exists(select 1 from public.inventory_items i where i.id=item_id));
revoke all on public.inventory_variants,public.inventory_barcodes,public.inventory_receipts,public.barcode_catalog_requests,public.inventory_creation_requests from public,anon,authenticated;
grant select on public.inventory_variants,public.inventory_barcodes,public.inventory_receipts to authenticated;

create function public.link_inventory_barcode(p_item_id uuid,p_code text,p_brand text,p_model text,p_units numeric)
returns uuid language plpgsql security definer set search_path='' as $$
declare site uuid; variant uuid; existing public.inventory_barcodes; result uuid;
begin
  if public.user_role() is distinct from 'admin' then raise exception 'Solo administracion puede asociar codigos'; end if;
  if p_code is null or p_code !~ '^[!-~]{1,128}$' or length(trim(coalesce(p_brand,''))) not between 1 and 80
    or p_model is null or length(p_model)>80 or p_units is null or p_units<=0 or p_units>999999 or p_units<>round(p_units,3) then raise exception 'Revisa codigo, marca y unidades por envase'; end if;
  perform pg_advisory_xact_lock(90714001);
  select i.headquarters_id into site from public.inventory_items i join public.headquarters h on h.id=i.headquarters_id and h.is_active where i.id=p_item_id;
  if not found then raise exception 'Articulo o sede no disponible'; end if;
  insert into public.inventory_variants(item_id,brand,model) values(p_item_id,trim(p_brand),trim(p_model))
    on conflict(item_id,brand,model) do nothing;
  select id into variant from public.inventory_variants where item_id=p_item_id and brand=trim(p_brand) and model=trim(p_model);
  select * into existing from public.inventory_barcodes where headquarters_id=site and code=p_code;
  if found then
    if existing.variant_id<>variant or existing.units_per_pack<>p_units then raise exception 'Este codigo ya esta asociado a otro producto o envase en la sede'; end if;
    return existing.id;
  end if;
  insert into public.inventory_barcodes(headquarters_id,item_id,variant_id,code,units_per_pack)
    values(site,p_item_id,variant,p_code,p_units) returning id into result;
  insert into public.inventory_item_history(item_id,actor_id,event_type,details)
    values(p_item_id,auth.uid(),'barcode_linked',jsonb_build_object('code',p_code,'brand',trim(p_brand),'model',trim(p_model),'units_per_pack',p_units));
  return result;
end $$;

-- One transaction covers all destinations. The receipt identifier survives retries.
create function public.receive_inventory_barcode(p_id uuid,p_barcode_id uuid,p_packs numeric,p_lot_code text,p_expiration date,p_allocations jsonb,p_notes text)
returns numeric language plpgsql security definer set search_path='' as $$
declare b public.inventory_barcodes; v public.inventory_variants; old public.inventory_receipts;
  payload jsonb; total numeric; allocated numeric:=0; part jsonb; amount numeric; lot uuid; balance numeric;
begin
  if public.user_role() is distinct from 'admin' then raise exception 'Solo administracion puede registrar entradas'; end if;
  if p_id is null or p_packs is null or p_packs<=0 or p_packs>99999999999 or p_packs<>trunc(p_packs)
    or p_lot_code is null or length(p_lot_code)>80 or length(trim(coalesce(p_notes,''))) not between 3 and 1000
    or p_allocations is null or jsonb_typeof(p_allocations)<>'array' then raise exception 'Revisa envases, lote, motivo y reparto'; end if;
  if jsonb_array_length(p_allocations) not between 1 and 100 then raise exception 'Elige entre 1 y 100 destinos'; end if;
  payload=jsonb_build_object('barcode_id',p_barcode_id,'packs',p_packs,'lot_code',p_lot_code,'expiration',p_expiration,'allocations',p_allocations,'notes',p_notes);
  perform pg_advisory_xact_lock(90714001);
  select * into old from public.inventory_receipts where id=p_id;
  if found then
    if old.actor_id<>auth.uid() or old.payload<>payload then raise exception 'Identificador reutilizado con datos distintos'; end if;
    return old.balance_after;
  end if;
  select * into b from public.inventory_barcodes where id=p_barcode_id;
  if not found then raise exception 'Codigo no encontrado'; end if;
  if p_expiration is null and exists(select 1 from public.inventory_items i
    join public.inventory_template_fields f on f.template_id=i.template_id
    join public.inventory_fields d on d.id=f.field_id
    where i.id=b.item_id and f.is_required and d.field_key='expiration_date') then
    raise exception 'La ficha de este articulo exige fecha de caducidad para cada lote';
  end if;
  select * into v from public.inventory_variants where id=b.variant_id;
  total=p_packs*b.units_per_pack;
  if total>99999999999.999 or total<>round(total,3) then raise exception 'Cantidad total fuera de rango'; end if;
  for part in select value from jsonb_array_elements(p_allocations) loop
    amount=(part->>'quantity')::numeric;
    if amount is null or amount<=0 or amount>99999999999.999 or amount<>round(amount,3) then raise exception 'Cada destino necesita una cantidad positiva con hasta 3 decimales'; end if;
    allocated=allocated+amount;
  end loop;
  if allocated<>total then raise exception 'El reparto no coincide con las unidades recibidas'; end if;
  insert into public.inventory_stock_lots(item_id,variant_id,code,expiration_date)
    values(b.item_id,b.variant_id,left(v.brand||case when v.model<>'' then ' / '||v.model else '' end,40)||' / '||
      left(coalesce(nullif(trim(p_lot_code),''),'Recepcion '||current_date),34)||' / '||p_id::text,p_expiration) returning id into lot;
  for part in select value from jsonb_array_elements(p_allocations) loop
    balance=public.manage_inventory_stock(gen_random_uuid(),b.item_id,'in',null,lot,
      nullif(part->>'location_id','')::uuid,nullif(part->>'container_id','')::uuid,(part->>'quantity')::numeric,
      'Recepcion '||p_id::text||': '||p_notes);
  end loop;
  insert into public.inventory_receipts(id,item_id,actor_id,payload,balance_after) values(p_id,b.item_id,auth.uid(),payload,balance);
  insert into public.inventory_item_history(item_id,actor_id,event_type,details)
    values(b.item_id,auth.uid(),'barcode_received',payload||jsonb_build_object('variant_id',v.id,'brand',v.brand,'model',v.model,'code',b.code,'units_per_pack',b.units_per_pack,'total',total,'receipt_id',p_id));
  return balance;
end $$;

create function public.request_barcode_cataloging(p_id uuid,p_site uuid,p_code text,p_description text,p_packs numeric)
returns uuid language plpgsql security definer set search_path='' as $$
declare old public.barcode_catalog_requests; payload jsonb; request uuid; r text;
begin
  r=public.user_role();
  if r is null or (r<>'admin' and p_site is distinct from public.user_headquarters_id()) then raise exception 'No puedes solicitar en esta sede'; end if;
  if not exists(select 1 from public.headquarters where id=p_site and is_active) then raise exception 'Sede inactiva'; end if;
  if p_id is null or p_code is null or p_code !~ '^[!-~]{1,128}$' or length(trim(coalesce(p_description,''))) not between 3 and 1000
    or p_packs is null or p_packs<=0 or p_packs>999999999 or p_packs<>trunc(p_packs) then raise exception 'Revisa codigo, descripcion y envases'; end if;
  payload=jsonb_build_object('site',p_site,'code',p_code,'description',p_description,'packs',p_packs);
  perform pg_advisory_xact_lock(90714001);
  select * into old from public.barcode_catalog_requests where id=p_id;
  if found then
    if old.actor_id<>auth.uid() or old.payload<>payload then raise exception 'Identificador reutilizado'; end if;
    return old.request_id;
  end if;
  insert into public.logistics_requests(headquarters_id,created_by,material,quantity,unit,notes)
    values(p_site,auth.uid(),'Catalogar: '||left(trim(p_description),140),p_packs,'envases',
      'PENDIENTE DE CATALOGACION. No se ha registrado stock. Codigo: '||p_code||E'\n'||p_description) returning id into request;
  insert into public.barcode_catalog_requests values(p_id,auth.uid(),payload,request);
  return request;
end $$;

create function public.create_inventory_record_once(p_id uuid,p_record jsonb)
returns uuid language plpgsql security definer set search_path='' as $$
declare old public.inventory_creation_requests; item uuid;
begin
  if public.user_role() is null or public.user_role() not in ('admin','editor','operator') or
    (public.user_role()<>'admin' and (p_record->>'headquarters_id')::uuid is distinct from public.user_headquarters_id()) then raise exception 'No puedes crear en esta sede'; end if;
  if p_id is null or coalesce((p_record->>'current_stock')::numeric,0)<>0 then raise exception 'Esta alta de catalogo debe empezar sin stock'; end if;
  perform pg_advisory_xact_lock(90714001);
  select * into old from public.inventory_creation_requests where id=p_id;
  if found then
    if old.actor_id<>auth.uid() or old.payload<>p_record then raise exception 'Identificador de alta reutilizado'; end if;
    return old.item_id;
  end if;
  item=public.create_inventory_record(p_record,null,0,null);
  insert into public.inventory_creation_requests values(p_id,auth.uid(),p_record,item);
  return item;
end $$;

revoke execute on function public.link_inventory_barcode(uuid,text,text,text,numeric),
  public.receive_inventory_barcode(uuid,uuid,numeric,text,date,jsonb,text),public.request_barcode_cataloging(uuid,uuid,text,text,numeric),
  public.create_inventory_record_once(uuid,jsonb) from public,anon,authenticated;
grant execute on function public.link_inventory_barcode(uuid,text,text,text,numeric),
  public.receive_inventory_barcode(uuid,uuid,numeric,text,date,jsonb,text),public.request_barcode_cataloging(uuid,uuid,text,text,numeric),
  public.create_inventory_record_once(uuid,jsonb) to authenticated;
notify pgrst,'reload schema';
$iae_ddl$;
insert into iae_internal.migrations(version) values('202609170001_barcode_receiving.sql');
end if;
end $iae_apply$;

do $iae_apply$ begin
if not exists(select 1 from iae_internal.migrations where version='202609180001_product_research.sql') then
execute $iae_ddl$-- Preserve user-reviewed provenance in the same transaction as the zero-stock creation.
-- This records a user's source declaration, not independent product verification.
create function public.create_inventory_record_from_product(p_id uuid,p_record jsonb,p_source jsonb)
returns uuid language plpgsql security definer set search_path='' as $$
declare item uuid; code text; checksum integer;
begin
  if p_id is null or jsonb_typeof(p_record) is distinct from 'object' then raise exception 'Alta de producto no valida'; end if;
  if p_source is null or jsonb_typeof(p_source)<>'object' or length(p_source::text)>512 or
    (select count(*) from jsonb_object_keys(p_source))<>4 or
    coalesce(p_source->>'provider','') not in ('upcitemdb','openfoodfacts') or
    p_source->'reviewed' is distinct from 'true'::jsonb or
    jsonb_typeof(p_source->'code') is distinct from 'string' or
    jsonb_typeof(p_source->'fetchedAt') is distinct from 'string' then
    raise exception 'Fuente revisada no valida';
  end if;
  code=p_source->>'code';
  if code !~ '^(\d{8}|\d{12}|\d{13}|\d{14})$' or code ~ '^0+$' then raise exception 'Codigo de producto no valido'; end if;
  select sum(substr(code,n,1)::integer * case when (length(code)-n)%2=1 then 3 else 1 end)
    into checksum from generate_series(1,length(code)-1) n;
  if (10-checksum%10)%10<>right(code,1)::integer then raise exception 'Codigo de producto no valido'; end if;
  if p_source->>'fetchedAt' !~ '^\d{4}-\d{2}-\d{2}T' then raise exception 'Fecha de consulta no valida'; end if;
  perform (p_source->>'fetchedAt')::timestamptz;
  perform pg_advisory_xact_lock(90714001);
  -- The existing RPC enforces role, site, field validation and exact-payload retries.
  item=public.create_inventory_record_once(p_id,p_record||jsonb_build_object('_online_source',p_source));
  if not exists(select 1 from public.inventory_item_history where item_id=item and event_type='online_product_review') then
    insert into public.inventory_item_history(item_id,actor_id,event_type,details)
      values(item,auth.uid(),'online_product_review',jsonb_build_object('source',p_source));
  end if;
  return item;
end $$;

revoke execute on function public.create_inventory_record_from_product(uuid,jsonb,jsonb) from public,anon,authenticated;
grant execute on function public.create_inventory_record_from_product(uuid,jsonb,jsonb) to authenticated;
notify pgrst,'reload schema';
$iae_ddl$;
insert into iae_internal.migrations(version) values('202609180001_product_research.sql');
end if;
end $iae_apply$;
commit;
