const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const migrations = [
  '202609140001_security_and_operations.sql',
  '202609140002_logistics_requests.sql',
  '202609140003_documents_and_validation.sql',
  '202609150001_request_articles.sql',
  '202609150002_function_security.sql',
  '202609150003_container_checklists.sql',
  '202609160001_distributed_stock.sql',
  '202609170001_barcode_receiving.sql',
  '202609180001_product_research.sql'
];
const tracking = `create schema if not exists iae_internal;
revoke all on schema iae_internal from public;
create table if not exists iae_internal.migrations(version text primary key,applied_at timestamptz not null default now());
`;
const renderUpdates = files => files.map(file => {
  const sql = fs.readFileSync(path.join(root, 'supabase/migrations', file), 'utf8')
    .replace(/^begin;\s*/i, '').replace(/commit;\s*$/i, '');
  return `do $iae_apply$ begin
if not exists(select 1 from iae_internal.migrations where version='${file}') then
execute $iae_ddl$${sql}$iae_ddl$;
insert into iae_internal.migrations(version) values('${file}');
end if;
end $iae_apply$;`;
}).join('\n\n');
const header = '-- Generated by node scripts/build-sql.cjs. Run in Supabase SQL Editor as postgres.\n';
const updates = renderUpdates(migrations);
fs.writeFileSync(path.join(root, 'supabase/upgrade-product-research.sql'), header + 'begin;\n' + tracking + updates + '\ncommit;\n');
fs.writeFileSync(path.join(root, 'supabase/upgrade-barcode-receiving.sql'), header + 'begin;\n' + tracking + updates + '\ncommit;\n');
fs.writeFileSync(path.join(root, 'supabase/upgrade-distributed-stock.sql'), header + 'begin;\n' + tracking + updates + '\ncommit;\n');
fs.writeFileSync(path.join(root, 'supabase/upgrade-2026-09-14.sql'), header + 'begin;\n' + tracking + renderUpdates(migrations.slice(0, 3)) + '\ncommit;\n');
fs.writeFileSync(path.join(root, 'supabase/upgrade-2026-09-15.sql'), header + 'begin;\n' + tracking + updates + '\ncommit;\n');
fs.writeFileSync(path.join(root, 'supabase/upgrade-checklists-2026-09-15.sql'), header + 'begin;\n' + tracking + updates + '\ncommit;\n');
fs.writeFileSync(path.join(root, 'supabase/fix-security-warnings-2026-09-15.sql'), header + '-- Existing projects with the September 14 upgrade applied. No inventory data changes.\n' + 'begin;\n' + tracking + renderUpdates(migrations.slice(4,5)) + '\ncommit;\n');
fs.writeFileSync(path.join(root, 'supabase/install.sql'), header + '-- NEW EMPTY DATABASES ONLY. Existing projects: use upgrade-2026-09-15.sql.\n' + 'begin;\n' + fs.readFileSync(path.join(root, 'supabase/schema.sql'), 'utf8') + '\n' + tracking + updates + '\ncommit;\n');
console.log('Generated installer and upgrades for 2026-09-14 and 2026-09-15');
